logging:
  level:
    com.terrakorea.assignment: DEBUG

spring:
  application:
    name: assignment
  description: open-api
  version: 1.0
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:10000/assign
    username: root
    password: testassign

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
    open-in-view: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
server:
  port: 9000