CREATE TABLE TEST_ENTITY
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPU_USAGE    DOUBLE,
    CREATED_DATE DATE,
    CREATED_TIME TIME
);
CREATE TABLE CPU_USAGE_TABLE
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPU_USAGE    DOUBLE,
    CREATED_DATE DATE,
    CREATED_TIME TIME
);